const SET_COUNTRIES_LIST = 'SET_COUNTRIES_LIST';
const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';
const SET_SELECTED_TRANSLATION = 'SET_SELECTED_TRANSLATION';


export {
    SET_COUNTRIES_LIST, 
    SET_SELECTED_COUNTRY, 
    SET_SELECTED_TRANSLATION
}