const PLAYERS_COUNT_SUBMIT = "PLAYERS_COUNT_SUBMIT";
const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
const SET_PLAYER_NAME = 'SET_PLAER_NAME';
const SET_PLAYER_DATA= 'SET_PLAYER_DATA';
const SET_PLAYERS_SELECTED = "SET_PLAYERS_SELECTED";
const SET_RESET_PLAYER = "SET_RESET_PLAYER"
const SET_PLAYER_INFO = 'SET_PLAYER_INFO';
const SET_WINNER_INFO = "SET_WINNER_INFO";
const RESET_BATTLE = "RESET_BATTLE"

export {
    PLAYERS_COUNT_SUBMIT, 
    SET_PLAYER_NAME, 
    SET_ERROR_MESSAGE, 
    SET_PLAYER_DATA, 
    SET_PLAYER_INFO,
    SET_PLAYERS_SELECTED,
    SET_RESET_PLAYER,
    SET_WINNER_INFO,
    RESET_BATTLE
    
}
